### PR TITLE
fail gracefully when dat share is already running fixes #561

### LINKED ISSUE #561: dat should fail gracefully if another dat is already open on that dir
1. Run a dat in one directory (`dat path/to/files`)
2. Open a new terminal
3. Run a dat on that same directory (`dat path/to/files`)

It tries to open the db but its already open. It should probably fail gracefully (give a nice message) or use level-party to just open it anyway even though there's another one up already

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: lock tweet-data/.dat/LOCK: Resource temporarily unavailable
    at /Users/karissa/node_modules/dat/node_modules/levelup/lib/levelup.js:119:34
    at /Users/karissa/node_modules/dat/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

### PR DESCRIPTION
**Pull request by karissa**
fixes #561

### CODE REVIEW

**Comment by joehand** [comment]
Looks good to me! Thanks for putting those error functions in one place!

**Comment by maxogden** [comment]
Nice and simple, do we need a test?

**Comment by karissa** [comment]
I tried adding a test but couldn't figure out how to trigger it, the simple stupid way of running a dat instance, not closing it, and opening another one with the same command was not working.

**Comment by juliangruber** [comment]
> I tried adding a test but couldn't figure out how to trigger it, the simple stupid way of running a dat instance, not closing it, and opening another one with the same command was not working.

did you try with a child process too?

**Comment by joehand** [comment]
added a test

**Comment by karissa** [comment]
thanks @joehand ! I forgot the `{end: false}!`

**Pull request merged**
