### PR TITLE
Add a few things to `dat status`

### PR DESCRIPTION
**Pull request by joehand**
Add discovery key and if the dat is writable.

```
❯ dat status
dat://778f8d955175c92e4ced5e4f5563f69bfec0c86cc6f670352c457943666fe639
Discovery Key: 25a78aa81615847eba00995df29dd41d7ee30f3b01f892209f79b75a57d989e1
You can write to this dat.
2 files (1.4 MB)
Version: 6
```

### CODE REVIEW

**Comment by karissa** [comment]
Sorry I missed it, what does the discovery give to the user? What's the use case?

**Comment by joehand** [comment]
Main use case right now is trying to find your secret key. But generally useful for debugging, since we use discovery key a lot and it is very hard to get it out from the file directly.

There may be a better place for this but this command isn't doing much yet.

**Comment by joehand** [comment]
Main use case right now is trying to find your secret key. But generally useful for debugging, since we use discovery key a lot and it is very hard to get it out from the file directly.

There may be a better place for this but this command isn't doing much yet.

**Comment by karissa** [comment]
OK sure, but might be useful to have a `dat keys` command or something to get all the key data out. I just feel like this is going to raise a bunch of q's from users about what 'discovery key' means

**Comment by joehand** [comment]
> OK sure, but might be useful to have a dat keys command or something to get all the key data out.

Good idea! Gonna use that as a starting point for this and the secret key management.

**Pull request closed without merging**
