### PR TITLE
Update registry commands, unpublish, add some nicer messages

### PR DESCRIPTION
**Pull request by joehand**
* Fixed some bugs in the registry commands
* Use dat.json better again for publish + unpublish
* Add unpublish
- [x] fix expired jwt token msg #791

Login:

screen shot 2017-05-30 at 18 57 26

Publish:
screen shot 2017-05-30 at 18 57 40

Unpublish
screen shot 2017-05-30 at 18 57 56

### CODE REVIEW

**Comment by pfrazee** [comment]
Per our IRC conversation --

Could we add a `Registry: ` or `Server: ` line to the login process, which has a default value of `datproject.org`? I think it's pretty important to convey that datproject.org is a good default, but not *hardwired* into dat cli.

**Comment by karissa** [comment]
It'd be cool if you could do `dat publish <server>` which would be a proxy for --server=

I think in the `dat publish` text, instead of 'datproject.org will live update when you are syncing your dat', maybe it could say something with the actual command with color: 'Don't forget to keep your data online by using `dat share` before sharing your link'

**Comment by joehand** [comment]
Okay, I'll do a few updates:

- [ ]`dat login` and `dat register` requires server option (either `dat login datproject.org` or `dat login --server datproject.org`).
   - [ ] if `server` not specified then prompt for server
   - [ ] default to `datproject.org` as server on prompt
- [ ] `dat publish`, `dat logout`, and `dat whoami`:
  - [ ] print your current server (obtained from current login via township) 
  - [ ] run command to that server
  - [ ] (?) `dat publish`: print published URL. We need server to send us back this link. (it'd be good to add the published link to `dat.json`, but we need spec for that).

Other bugs:

- [ ] fix language in `dat publish` re karissa feedback
- [ ] make sure references to `datproject.org` reference login server
- [ ] use `~/.datrc` instead of `~/.townshiprc`. 
- [ ] store server root in config? (currently it is storing `"server": "https://datproject.org/api/v1"`)

> It'd be cool if you could do dat publish <server> which would be a proxy for --server=

Yea, I'll do that for `dat login`. Currently, you have to already be logged in for `dat publish` to work. It'd be cool to prompt for login but not gonna add that for now.

**Comment by joehand** [comment]
Okay, here is what I have for `dat login` and `dat register` (note, these require https://github.com/datproject/dat-registry-client/pull/4)

Default login without server argument:
screen shot 2017-05-31 at 11 20 10

Default login with server argument:
screen shot 2017-05-31 at 11 20 31

Register to another server:
screen shot 2017-05-31 at 11 27 08

Login to another server:
screen shot 2017-05-31 at 11 27 39

**Comment by pfrazee** [comment]
Looks good!

**Comment by joehand** [comment]
Should be all addressed! All commands dealing with registry can take another server as first argument or use the current login as default (datproject.org or otherwise). Here are a few more caps:

screen shot 2017-05-31 at 13 26 11
screen shot 2017-05-31 at 14 20 57

**Comment by karissa** [comment]
woot!

**Pull request merged**
