### PR TITLE
Dat v14 -- breaking changes

### PR DESCRIPTION
**Pull request by okdistribute**
The *network* of dat v14 will not be compatible with earlier versions of dat. The .dat metadata file will still work, but older clients should upgrade to v14.

It will have big improvements:
* Better connectivity: A better DHT and holepunching. The networking stack has been entirely rewritten. See https://github.com/hyperswarm/hyperswarm
* Deprecating the `dat share` command. Now, `dat share` and `dat sync` do the same thing, so you no longer have to remember if your directory has a dat in it already.

### CODE REVIEW

**Comment by decentral1se** [comment]
Got myself a fresh copy of node v12.16.1 and tried to `npm install` this branch and got confronted with a whole slew of errors. Here are the logs below. Probably I'm doing it wrong :question: 

https://gist.github.com/decentral1se/8e45d5527c30414a8d2793b6e6a2999c

If I could get past this it'd be cool to test because I was struggling to get connectivity sorted from my homebrew here in the house. Thanks for the good work!

**Comment by okdistribute** [comment]
@decentral1se ah looks like it's still trying to install discovery-swarm. can you rm -rf node_modules and rm-rf package-lock.json, and then reinstall?

**Comment by decentral1se** [comment]
Unfortunately, I still explode into flames: https://gist.github.com/decentral1se/90322a42bb8112239a64dedf7edc1e7d. I can't seem to get all the logs (some stdout/stderr issue that escapes me now). Not sure what I'm doing TBH :)

**Comment by okdistribute** [comment]
@decentral1se it seems like you're still trying to install discovery-swarm for some reason. Are you on the right branch? `git checkout dat-nodev4`

**Comment by okdistribute** [comment]
@decentral1se Oh I figured it out, dat-doctor is installing discovery-swarm.

**Comment by okdistribute** [comment]
okay @decentral1se this should be ready for testing now, my apologies about missing that little detail

**Comment by decentral1se** [comment]
Yep that installs! I could share some test folders! It's a bit hard to test with friends who can't go through this installation procedure to check if we can share what was problematic to share before. Also the dat doctor is one now, so I can't check if those issues are resolved :) If this could go out on a new release of dat-desktop, I'd definitely be able to give it more testing.

**Comment by christianbundy** [comment]
Installs and passes test over here. :tada:

**Pull request merged**
