### PR TITLE
fix download speed after finish

### LINKED ISSUE #508: Download speed should be removed immediately after finishing
Right now it continues to show download speed even though its already done for a few log cycles. It should not display if its not actively downloading or finished.

### PR DESCRIPTION
**Pull request by juliangruber**
closes #508

### CODE REVIEW

**Comment by juliangruber** [comment]
i have a hunch though that this isn't the cleanest solution...the problem isn't that the interval is still going, the problem is that the swarm stats still thinks there's download activity. if you agree i'll change it to that

**Comment by joehand** [comment]
Oh interesting solution. The interval is printing out peer # and upload speed as well, and we'd want to keep printing those. And if the Dat updates then we need to start the interval again to print new downloads.

I also made a fix attempt in the dat-js branch, I overwrote the speedometer since that was the thing causing the issue ([this commit](https://github.com/datproject/dat/pull/509/commits/dc312231660810e19ee08006f0d518d7ae4808a7)). But it also felt like not the cleanest thing. Sorry, I meant to add that as a comment to my issue.

**Comment by juliangruber** [comment]
> And if the Dat updates then we need to start the interval again to print new downloads.

in that case, would the line that it's safe to ctrl+c now be removed as well?

**Comment by joehand** [comment]
> in that case, would the line that it's safe to ctrl+c now be removed as well?

Definitely! [Added that](https://github.com/datproject/dat/commit/a7ff2014452397077da0d0016d3807dab9422570)

**Comment by joehand** [comment]
Thinking about it a bit more, I'm not sure there is a case right now where we'd want to clear the interval. Unless you exit, you always have the possibility of displaying & updating:

* Number of connections
* Upload speed

We want to keep both of those around even if the download is finished.

**Comment by juliangruber** [comment]
makes sense!

**Pull request closed without merging**
